_wandb:
    value:
        cli_version: 0.21.0
        e:
            xmm798duil2ue7ywnnzvd13ly8tpllnb:
                codePath: testbook.ipynb
                codePathLocal: testbook.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "484937371648"
                        used: "201002512384"
                email: nevedya.gwalani2024@vitstudent.ac.in
                executable: c:\Users\neved\sendhelp\plant-leaf-disease-classifier\venv\Scripts\python.exe
                git:
                    commit: 58a3436dcfb43cc057abff5c6d97d1c6a53aa4c4
                    remote: https://github.com/NiviDevs/plant-leaf-disease-classifier.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-f545f0a6-3fc1-4f0b-1cac-de4c954fcc44
                host: Excalibur
                memory:
                    total: "16370769920"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\neved\sendhelp\plant-leaf-disease-classifier\testbook.ipynb
                python: CPython 3.12.8
                root: c:\Users\neved\sendhelp\plant-leaf-disease-classifier
                startedAt: "2025-07-22T20:07:01.858576Z"
                writerId: xmm798duil2ue7ywnnzvd13ly8tpllnb
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 105
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 105
            "3":
                - 1
                - 2
                - 16
            "4": 3.12.8
            "5": 0.21.0
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
architecture:
    value: HybridCNNTransformer
batch_size:
    value: 32
epochs:
    value: 4
image_size:
    value: 224
learning_rate:
    value: 0.0001
